{% set name = "pystac-io" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystac-io-{{ version }}.tar.gz
  sha256: 021ba6b3a575ae6e25d4be134f1106a16e02dedad27995301aa4c4e0305a059a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  skip: true # [py<36]

requirements:
  host:
    - pip
    - python
  run:
    - pystac >=0.5.2
    - python

test:
  imports:
    - pystac_io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/azavea/pystac-io
  summary: Python library providing additional IO implementations for PySTAC
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CloudNiner
